name: 720degrees
dependencies:
  - python=3.9.12
  - pip=22.3.1
  - pip:
    - fastapi==0.88.0
    - fastapi-sqlalchemy==0.2.1
    - alembic==1.8.1
    - httpx==0.23.1
    - pandas==1.5.2
    - sqlalchemy_utils==0.38.3
    - psycopg2==2.9.5
    - python-dotenv==0.21.0
    - uvicorn==0.20.0
